title: Pre-Fortress 2 - RSS Feed
email: staff@prefortress.com
description: >- # this means to ignore newlines until "baseurl:"
  Pre-Fortress 2 is a TF2 sourcemod that caters to the gameplay of earlier Team Fortress installments 
  while maintaining the aesthetics from TF2's older designs from 2006.
  Grenades, armor, and cut content are all back to create a nostalgic Team Fortress experience! 
  Visit the reimagined world of classic maps such as Crossover and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prefortress.com" # the base hostname & protocol for your site, e.g. http://example.com
discord-invite: "https://prefortress.com/discord/"
gameversion: "073" # current game version

# Google Analytics
google_analytics: G-Q8T3T3HDGV

# Build settings
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

feed:
  categories: 
    - updates
    - blog  

  posts_limit: 100