title: Pre-Fortress 2 Website
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prefortress.com" # the base hostname & protocol for your site, e.g. http://example.com
discord-invite: "https://discord.gg/ra68rM5nuE"

# Google Analytics
google_analytics: G-Q8T3T3HDGV

# Build settings
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from